# Generated by Django 5.0.6 on 2024-06-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Honeydue', '0002_remove_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
