# Generated by Django 5.0.6 on 2024-05-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocketGuard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
