# Generated by Django 5.0.6 on 2024-05-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goodbudget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='user',
        ),
        migrations.AlterField(
            model_name='envelope',
            name='budget_amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='current_balance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
